//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASI.Basecode.Resources.Messages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Common {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Common() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ASI.Basecode.Resources.Messages.Common", typeof(Common).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A customer has responded to ticket #.
        /// </summary>
        public static string NotifToAgent {
            get {
                return ResourceManager.GetString("NotifToAgent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticket created successfully!.
        /// </summary>
        public static string SuccessCreateTicket {
            get {
                return ResourceManager.GetString("SuccessCreateTicket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully deleted ticket!.
        /// </summary>
        public static string SuccessDeleteTicket {
            get {
                return ResourceManager.GetString("SuccessDeleteTicket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully edited ticket!.
        /// </summary>
        public static string SuccessEditTicket {
            get {
                return ResourceManager.GetString("SuccessEditTicket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully reassigned ticket to.
        /// </summary>
        public static string SuccessReassign {
            get {
                return ResourceManager.GetString("SuccessReassign", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Successfully reassigned ticket to.
        /// </summary>
        public static string ViewFeedbackBtn
        {
            get
            {
                return ResourceManager.GetString("SuccessReassign", resourceCulture);
            }
        }
    }
}
